name: Build Android and iOS

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn install

    - name: Build Android
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload Android APK
      uses: actions/upload-artifact@v3
      with:
        name: Android APK
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 3

  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn install

    - name: Install Pods
      run: |
        cd ios
        pod install

    - name: Build iOS
      run: |
        cd ios
        xcodebuild -workspace Blockhouse.xcworkspace \
        -scheme Blockhouse \
        -sdk iphoneos \
        -configuration Release \
        clean build

    - name: Upload iOS Build
      uses: actions/upload-artifact@v3
      with:
        name: iOS Build
        path: ios/build
        retention-days: 3
