name: Lint and Test

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn install

    - name: Set up Expo CLI
      run: yarn global add expo-cli

    - name: Login to Expo
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: expo whoami

    - name: Run Lint
      run: yarn lint

    - name: Run Tests
      run: yarn test
